### ISSUE TITLE
Using Route Master

### ISSUE THREAD

**Issue by Jonathan002** [Jonathan002/route-master-example#1]
Hi guys, I'm looking to hear your thoughts on Route Master and if this tool was useful to you in any way. Although stating info is entirely voluntary it really helps my profile out if you are able provide the company name and the routing use case for your project, thanks! : )

**Comment by CapLonelyFlaw** [comment]
Hi! Awesome work. But. Is lay-router supports `[@routerTransition]`?
I see that you provide some duration Input that responsible for fade-in animation.
But what if i want custom animation with angular animations? [like in this post](https://medium.com/google-developer-experts/angular-supercharge-your-router-transitions-using-new-animation-features-v4-3-3eb341ede6c8)

**Comment by CapLonelyFlaw** [comment]
And where i can find source code of RouteMaster?
