### ISSUE TITLE
Latest Angular not working

### ISSUE THREAD

**Issue by samfrach** [Jonathan002/route-master-example#2]
Hello,
I'm using 8.2.8 and there are a lot of compilation problems about rxjs and rxjs-compat.

Is there still no issue to use auxiliary routes with lazy loaded modules ? so sad....

thank you

**Comment by Jonathan002** [comment]
Hi Samfrach, thanks for noting this. 

As of now I recommend you switch your Angular version to one of the 3 stable branches listed in this repository:

ng-8.1.2 - https://github.com/Jonathan002/route-master-example/tree/ng-8.1.2
ng-7.1.0 - https://github.com/Jonathan002/route-master-example/tree/ng-7.1.0
ng-6.1.0 - https://github.com/Jonathan002/route-master-example/tree/ng-6.1.0

I wish I could keep on making the latest Angular version always stable, but don't have enough time on me as of now. Will definitely try to keep a branch for each major release though. Hope this helps.

Best, Jonathan
